export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK='REMOVE_TASK';
export const COMPLETE_TASK='COMPLETE_TASK';
export const CHANGE_FILTER='CHANGE_FILTER';
export const EDIT_TASK='EDIT_TASK';
export const PRIORITY_FILTER_COMMON='PRIORITY_FILTER_COMMON';
export const PRIORITY_FILTER_IMPORTANT='PRIORITY_FILTER_IMPORTANT';
export const PRIORITY_FILTER_VERY_IMPORTANT='PRIORITY_FILTER_VERY_IMPORTANT';